places = ['kashmir','maldives','thailand','dubai','canada','japan']
print('og list:',places)
print('sorted list',sorted(places))
print('og list',places)
print('reverse sorted:',sorted(places,reverse=True))
print('og list',places)
places.reverse()
print('reversed list:',places)
places.reverse()
print('re-reversed list:',places)
places.sort()
print('sorted list:',places)
places.sort(reverse=True)
print('reverse sorted list:',places)